apiVersion: v1
kind: Pod
metadata:
  name: test
  version: v1
  namespace: test
  labels:
    version: test1
  annotations:
    alpha.istio.io/sidecar: ignore
spec:
  restartPolicy: Always
  nodeSelector:
    zone: test
  containers:
    - name: nginx4test
      image: nginx:latest
      imagePullPolicy: Never
      resources:
        requests:
          cpu: 0.1
          memory: 32Mi
        limits:
          cpu: 0.5
          memory: 32Mi
      ports:
        - containerPort: 80
          hostPort: 8888
          name: httpd
          protocol: tcp
      livenessProbe:
        httpGet:
          path: /
          port: 80
          host: 127.0.0.1
          scheme: HTTP
        initialDelaySeconds: 180
        timeoutSeconds: 5
        periodSeconds: 15
      lifecycle:
        postStart:
          exec:
            command:
              - 'sh'
              - 'yum upgrade -y'
        preStop:
          exec:
            command: [ 'service httpd stop' ]
      volumeMounts:
        - name: volume
          mountPath: /data
          readOnly: True
  volumes:
    - name: volume
      #meptyDir: {}
      hostPath:
        path: /opt