apiVersion: v1
kind: GpuJob
metadata:
  name: gpu
  namespace: default
spec:
  numProcess: 1
  numTasksPerNode: 5
  cpusPerTask: 6
  numGpus: 1
  scripts: [ './cublashello' ]
  volume: './volume'
  outputFile: 'gpu.out'
  errorFile: 'gpu.err'


#SBATCH --job-name=cublas
#SBATCH --partition=dgx2
#SBATCH --output=%j.out
#SBATCH --error=%j.err
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=6
#SBATCH --gres=gpu:1