apiVersion: v1
kind: GpuJob
metadata:
  name: gpu
  namespace: default
spec:
  numProcess: 1
  numTasksPerNode: 1
  cpusPerTask: 6
  numGpus: 1
  compileScripts: [
      "module load cuda/9.2.88-gcc-4.8.5",
      "nvcc gpu-job-test/cublashello.cu -o gpu-job-test/cublashello -lcublas"
  ]
  runScripts: [
      "module load cuda/9.2.88-gcc-4.8.5",
      "./gpu-job-test/cublashello",
  ]
  volume: D:/gpu
  outputFile: gpu.out
  errorFile: gpu.err
  username: stu633
  password: 8uhlGet%
  workDir: gpu-job-test


#SBATCH --job-name=cublas
#SBATCH --partition=dgx2
#SBATCH --output=%j.out
#SBATCH --error=%j.err
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=6
#SBATCH --gres=gpu:1