apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  minReplicas: 10
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicaSet # we only support replicaSet now
    name: php-apache
    namespace: test
  targetCPUUtilizationPercentage: 90